Implement ftl::inspect_iterator
ftlorg/ftl pull request #10
Opened 2020-08-23 08:39 UTC by Blinkuu

2020-08-23 08:50 UTC, Blinkuu commented
This is still WIP

2020-08-31 15:55 UTC, BIGbadEL requested changes

2020-08-31 15:55 UTC, BIGbadEL commented on include/ftl/array.hpp
> +  constexpr auto swap(array &other) noexcept -> void {
Template parameters should be passed explicitly.

2020-08-31 15:55 UTC, BIGbadEL commented on include/ftl/array.hpp
> +  [[nodiscard]] constexpr static auto from_iter(const inspect_iterator<Iter, Callable> &iter) -> array<Item, N> {
should be explicitly ftl::array.

2020-08-31 15:55 UTC, BIGbadEL commented on include/ftl/inspect_iterator.hpp
> +  [[nodiscard]] constexpr auto count_impl() const -> size_type {
noexcept?

2020-08-31 15:55 UTC, BIGbadEL commented on include/ftl/inspect_iterator.hpp
> +  [[nodiscard]] auto enumerate_impl() const -> enumerate_iterator<inspect_iterator<Iter, Callable>> {
noexcept?

2020-09-01 09:23 UTC, BIGbadEL approved these changes

2020-09-01 09:24 UTC, merged